require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ItinerariesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Itinerary. As you add validations to Itinerary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItinerariesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all itineraries as @itineraries" do
      itinerary = Itinerary.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:itineraries)).to eq([itinerary])
    end
  end

  describe "GET #show" do
    it "assigns the requested itinerary as @itinerary" do
      itinerary = Itinerary.create! valid_attributes
      get :show, {:id => itinerary.to_param}, valid_session
      expect(assigns(:itinerary)).to eq(itinerary)
    end
  end

  describe "GET #new" do
    it "assigns a new itinerary as @itinerary" do
      get :new, {}, valid_session
      expect(assigns(:itinerary)).to be_a_new(Itinerary)
    end
  end

  describe "GET #edit" do
    it "assigns the requested itinerary as @itinerary" do
      itinerary = Itinerary.create! valid_attributes
      get :edit, {:id => itinerary.to_param}, valid_session
      expect(assigns(:itinerary)).to eq(itinerary)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Itinerary" do
        expect {
          post :create, {:itinerary => valid_attributes}, valid_session
        }.to change(Itinerary, :count).by(1)
      end

      it "assigns a newly created itinerary as @itinerary" do
        post :create, {:itinerary => valid_attributes}, valid_session
        expect(assigns(:itinerary)).to be_a(Itinerary)
        expect(assigns(:itinerary)).to be_persisted
      end

      it "redirects to the created itinerary" do
        post :create, {:itinerary => valid_attributes}, valid_session
        expect(response).to redirect_to(Itinerary.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved itinerary as @itinerary" do
        post :create, {:itinerary => invalid_attributes}, valid_session
        expect(assigns(:itinerary)).to be_a_new(Itinerary)
      end

      it "re-renders the 'new' template" do
        post :create, {:itinerary => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested itinerary" do
        itinerary = Itinerary.create! valid_attributes
        put :update, {:id => itinerary.to_param, :itinerary => new_attributes}, valid_session
        itinerary.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested itinerary as @itinerary" do
        itinerary = Itinerary.create! valid_attributes
        put :update, {:id => itinerary.to_param, :itinerary => valid_attributes}, valid_session
        expect(assigns(:itinerary)).to eq(itinerary)
      end

      it "redirects to the itinerary" do
        itinerary = Itinerary.create! valid_attributes
        put :update, {:id => itinerary.to_param, :itinerary => valid_attributes}, valid_session
        expect(response).to redirect_to(itinerary)
      end
    end

    context "with invalid params" do
      it "assigns the itinerary as @itinerary" do
        itinerary = Itinerary.create! valid_attributes
        put :update, {:id => itinerary.to_param, :itinerary => invalid_attributes}, valid_session
        expect(assigns(:itinerary)).to eq(itinerary)
      end

      it "re-renders the 'edit' template" do
        itinerary = Itinerary.create! valid_attributes
        put :update, {:id => itinerary.to_param, :itinerary => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested itinerary" do
      itinerary = Itinerary.create! valid_attributes
      expect {
        delete :destroy, {:id => itinerary.to_param}, valid_session
      }.to change(Itinerary, :count).by(-1)
    end

    it "redirects to the itineraries list" do
      itinerary = Itinerary.create! valid_attributes
      delete :destroy, {:id => itinerary.to_param}, valid_session
      expect(response).to redirect_to(itineraries_url)
    end
  end

end
